master:
  image: bdorville/spark:2.4.3_2.7.3-bionic
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    # change to docker host when not on prod server
    SPARK_PUBLIC_DNS: localhost
    #SPARK_PUBLIC_DNS: 192.168.99.100
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data
    - ./executables:/usr/executables

worker:
  image: bdorville/spark:2.4.3_2.7.3-bionic
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    # change to docker host when not on prod server
    SPARK_PUBLIC_DNS: localhost
    #SPARK_PUBLIC_DNS: 192.168.99.100
  links:
    - master
    - zeppelin
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data
    - ./executables:/usr/executables

zeppelin:
  image: bdorville/zeppelin:0.8.1_2.4.3-bionic
  hostname: zeppelin
  environment:
    MASTER: spark://master:7077
    ZEPPELIN_PORT: 8000
  links:
    - master
  ports:
    - 4040:4040
    - 8000:8000
  volumes:
    - ./executables:/usr/executables
    - ./data:/tmp/data
    - ./notebooks:/usr/zeppelin-0.8.1/notebook

